#lang racket/base

(define SymbolKind-File 1)
(define SymbolKind-Module 2)
(define SymbolKind-Namespace 3)
(define SymbolKind-Package 4)
(define SymbolKind-Class 5)
(define SymbolKind-Method 6)
(define SymbolKind-Property 7)
(define SymbolKind-Field 8)
(define SymbolKind-Constructor 9)
(define SymbolKind-Enum 10)
(define SymbolKind-Interface 11)
(define SymbolKind-Function 12)
(define SymbolKind-Variable 13)
(define SymbolKind-Constant 14)
(define SymbolKind-String 15)
(define SymbolKind-Number 16)
(define SymbolKind-Boolean 17)
(define SymbolKind-Array 18)
(define SymbolKind-Object 19)
(define SymbolKind-Key 20)
(define SymbolKind-Null 21)
(define SymbolKind-EnumMember 22)
(define SymbolKind-Struct 23)
(define SymbolKind-Event 24)
(define SymbolKind-Operator 25)
(define SymbolKind-TypeParameter 26)

(provide (all-defined-out))

